/**
 * Aggregates all XpressPro FX API route modules under /api.
 */
import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import walletsRouter from "./wallets";
import tradesRouter from "./trades";
import managersRouter from "./managers";
import messagesRouter from "./messages";
import p2pRouter from "./p2p";
import assetsRouter from "./assets";
import supportRouter from "./support";
import kycRouter from "./kyc";
import withdrawalsRouter from "./withdrawals";
import depositsRouter from "./deposits";
import banksRouter from "./banks";
import cardsRouter from "./cards";
import promotionsRouter from "./promotions";
import billingRouter from "./billing";
import referralsRouter from "./referrals";
import adminRouter from "./admin";
import gasFeeRouter from "./gas-fee";
import platformConfigRouter from "./platform-config";
import liveChatRouter from "./live-chat";
import mailboxRouter from "./mailbox";
import adminExtendedRouter from "./admin-extended";
import adminPlatformRouter from "./admin-platform";
import adminUsersRouter from "./admin-users";
import adminP2PRouter from "./admin-p2p";
import moonpayRouter from "./moonpay";
import paystackRouter from "./paystack";
import coinbaseRouter from "./coinbase";
import notificationsRouter from "./notifications";
import adminNotificationsRouter from "./admin-notifications";
import withdrawalGasFeeRouter from "./withdrawal-gas-fee";
import authPasswordRouter from "./auth-password";
import authPinRouter from "./auth-pin";
import adminDepositsRouter from "./admin-deposits";
import educationRouter from "./education";
import mentorshipRouter from "./mentorship";
import smartVestRouter from "./smartvest";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(walletsRouter);
router.use(tradesRouter);
router.use(managersRouter);
router.use(messagesRouter);
router.use(p2pRouter);
router.use(assetsRouter);
router.use(supportRouter);
router.use(kycRouter);
router.use(withdrawalsRouter);
router.use(depositsRouter);
router.use(banksRouter);
router.use(cardsRouter);
router.use(promotionsRouter);
router.use(billingRouter);
router.use(referralsRouter);
router.use(adminRouter);
router.use(gasFeeRouter);
router.use(platformConfigRouter);
router.use(liveChatRouter);
router.use(mailboxRouter);
router.use(adminExtendedRouter);
router.use(adminPlatformRouter);
router.use(adminUsersRouter);
router.use(adminP2PRouter);
router.use(moonpayRouter);
router.use(paystackRouter);
router.use(coinbaseRouter);
router.use(notificationsRouter);
router.use(adminNotificationsRouter);
router.use(withdrawalGasFeeRouter);
router.use(authPasswordRouter);
router.use(authPinRouter);
router.use(adminDepositsRouter);
router.use(educationRouter);
router.use(mentorshipRouter);
router.use(smartVestRouter);

export default router;
