kind = "web"
previewPath = "/"
title = "NeXTrade"
version = "1.0.0"
id = "artifacts/nextrade"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25849

[services.development]
run = "pnpm --filter @workspace/nextrade run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nextrade", "run", "build" ]
publicDir = "artifacts/nextrade/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25849"
BASE_PATH = "/"
