kind = "api"
  previewPath = "/api/healthz"
  title = "API Server"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 8082
  name = "API Server"
  paths = ["/api"]

  [services.development]
  run = "PORT=8082 ENABLE_DEMO_AUTH=true sh -c 'cd /home/runner/workspace/artifacts/api-server && node ./build.mjs && node --enable-source-maps ./dist/index.mjs'"

  [services.production]

  [services.production.build]
  args = ["pnpm", "--filter", "@workspace/api-server", "run", "build"]

  [services.production.build.env]
  NODE_ENV = "production"

  [services.production.run]
  args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

  [services.production.run.env]
  PORT = "8080"
  NODE_ENV = "production"

  [services.production.health.startup]
  path = "/api/healthz"
